### ISSUE TITLE
"iteration zero"

### ISSUE THREAD

**Issue by slowy1st** [treeman1111/Particles#3]
PS: I'm the guy from the codereview site =)

I'm using the provided gradle wrapper and can't build the project, those two deps are missing:
        compile "org.junit.jupiter:junit-jupiter-api:5.0.0-RC3"
        compile "com.google.code.gson:gson:2.8.1"

When adding those, the html:compileGwt fails:
Loading inherited module 'com.dgb.particles.GdxDefinition'
   [ERROR] Unable to find 'com/dgb/particles/GdxDefinition.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
:html:compileGwt FAILED

Within intellij, the two deps don't get applied to the modules (using gw cleanIdea idea). The project compiles after adding those within intellij. 

You got a dependency to your local filesystem: /home/hjr1yw/Documentos/Particles/test.json. When changing this one to the test.json in the path, I can launch the DesktopLauncher.

Edit: The 'common quasi standard' for project layouts is the maven layout: src/main/java, src/main/resources, src/test/java, src/test/resources. Not sure, but somehow it looks like the project setup is "f-ed" up. E.g. the ColorDeserializer is within the package main.java.engine...

**Comment by treeman1111** [comment]
Hey! Thanks for checking this out. Sorry that you had to deal with that to get it up and running :disappointed:. I'm not very good with Gradle. How should I go about resolving that problem? The import works fine if I use 'File -> New -> Project from version control -> GitHub'.  I'll fix the fs dependency.

**Comment by treeman1111** [comment]
Does this solve the issue? ed4caccf4b2ce5c7caec17f17a993de354800f2b

**Comment by slowy1st** [comment]
Yeah, the gradlew build and also intellij work fine now =)

**Comment by treeman1111** [comment]
Sweet!
